### ISSUE TITLE
Wear OS App crashes on calling Fetch API (or XMLHttpRequest)

### ISSUE THREAD

**Issue by fegodev** [renative-org/renative#615]
Hi! Nice work!

I am planning on developing a standalone Wear OS app with renative. I can run the debug version on the emulator and my test device.

However, the moment I initiate a `fetch` call the app crashes immediately.
```js
const response = await fetch('http://someurl.com')
```
Same problem occurs when using `XMLHttpRequest`.

See logs below. It appears that it's accessing `android.webkit` API which I think is not available on Wear OS.
```
    --------- beginning of crash
2020-11-22 16:27:58.592 7398-7472/? E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.test.app, PID: 7398
    java.lang.UnsupportedOperationException
        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:241)
        at android.webkit.CookieManager.getInstance(CookieManager.java:40)
        at com.facebook.react.modules.network.ForwardingCookieHandler.getCookieManager(ForwardingCookieHandler.java:178)
        at com.facebook.react.modules.network.ForwardingCookieHandler.get(ForwardingCookieHandler.java:56)
        at okhttp3.JavaNetCookieJar.loadForRequest(JavaNetCookieJar.java:61)
        at com.facebook.react.modules.network.ReactCookieJarContainer.loadForRequest(ReactCookieJarContainer.java:43)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:84)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

How can I make HTTP requests inside a renative Wear OS project?

Thanks!

**Comment by pavjacko** [comment]
@fegodev unfortunately android wear OS does not support webview API. more info here:
https://developer.android.com/guide/webapps/managing-webview.

So non webkit workaround would be needed for this. will need to check if there are libs out there which do not use android.webkit

**Comment by fegodev** [comment]
Yeah I figured. I couldn't find a React Native module for webkit independent requests so I started building my own. It implements the Google Volley library: https://github.com/google/volley

First test was successful on Wear OS with renative. Will keep you posted.

**Comment by pavjacko** [comment]
awesome. 👍 . If it works, it could potentially be used to patch RN metro which also relies on webkit thus direct debugging is not possible on androidwear atm.

**Comment by fegodev** [comment]
@pavjacko I have published a first version:
https://github.com/fegodev/react-native-volley

Not sure if it helps with the metro debugging problem but it can handle HTTP requests independent of webkit. Worked for me with renative on Wear OS device.

**Comment by pavjacko** [comment]
@fegodev awesome! will look into ways to integrate it for `0.33`

**Comment by rfestag** [comment]
@fegodev - Until this is integrated into 0.33, do you have an example of using it in WearOS? I tried pulling it in, and I'm seeing some odd behavior:

1. If I `console.error(Object.keys(Volley))`, I get `['fetch']` as would be expected
2. When i try to call `Volley.fetch`, I get **Cannot read property 'fetch' of null**, which is certainly odd considering the log clearly shows a non-null object with a `fetch` property

**Comment by rfestag** [comment]
Nevermind, I forgot to save the changes to my `renative.json` to register the plugin.

**Comment by A-Mostafa-B** [comment]
> Nevermind, I forgot to save the changes to my `renative.json` to register the plugin.

How can i register the plugin?

i installed react-native-volley and did as documentation, but not working for me and i don't know how to get debug console log to see what is going on
