### ISSUE TITLE
Adding a new yarn dependency breaks the android build

### ISSUE THREAD

**Issue by kevindsky** [renative-org/renative#662]
**Describe the bug**
Running `rnv run -p android` throws an error.

**To Reproduce**
1. Create new project
2. `rnv` run then android (the app deploys & runs at this stage)
3. Kill the server
4. `yarn add crypto-js` (or any other js library)
5. Repeat step 2

**Expected behavior**
It should build successfully.

**Screenshots or copy&paste**
```
./gradlew assembleDebug -x bundleReleaseJsAndAssets

FAILED with ERROR:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-community-viewpager:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings
62 actionable tasks: 1 executed, 61 up-to-date

BUILD FAILED in 16s

Command failed with exit code 1 (EPERM): ./gradlew assembleDebug -x bundleReleaseJsAndAssets

/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:10: error: package android.support.v4.view does not exist
import android.support.v4.view.PagerAdapter;
                              ^
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:11: error: package android.support.v4.view does not exist
import android.support.v4.view.ViewPager;
                              ^
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:29: error: cannot find symbol
public class ReactViewPager extends ViewPager {
                                    ^
  symbol: class ViewPager
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:31: error: cannot find symbol
  private class Adapter extends PagerAdapter {
                                ^
  symbol:   class PagerAdapter
  location: class ReactViewPager
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:64: error: cannot find symbol
    void removeAllViewsFromAdapter(ViewPager pager) {
                                   ^
  symbol:   class ViewPager
  location: class ReactViewPager.Adapter
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:107: error: package ViewPager does not exist
  private class PageChangeListener implements ViewPager.OnPageChangeListener {
                                                       ^
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPagerManager.java:27: error: type argument ReactViewPager is not within bounds of type-variable T
public class ReactViewPagerManager extends ViewGroupManager<ReactViewPager> {
                                                            ^
  where T is a type-variable:
    T extends ViewGroup declared in class ViewGroupManager
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPagerManager.java:117: error: cannot find symbol
    pager.setPageMargin((int) PixelUtil.toPixelFromDIP(margin));
         ^
  symbol:   method setPageMargin(int)
  location: variable pager of type ReactViewPager
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:38: error: cannot find symbol
      notifyDataSetChanged();
      ^
  symbol:   method notifyDataSetChanged()
  location: class ReactViewPager.Adapter
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:43: error: cannot find symbol
      notifyDataSetChanged();
      ^
  symbol:   method notifyDataSetChanged()
  location: class ReactViewPager.Adapter
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:52: error: cannot find symbol
      notifyDataSetChanged();
      ^
  symbol:   method notifyDataSetChanged()
  location: class ReactViewPager.Adapter
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:76: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:81: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:85: error: cannot find symbol
        POSITION_NONE : mViews.indexOf(object);
        ^
  symbol:   variable POSITION_NONE
  location: class ReactViewPager.Adapter
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:88: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:91: error: cannot find symbol
      container.addView(view, 0, generateDefaultLayoutParams());
                                 ^
  symbol:   method generateDefaultLayoutParams()
  location: class ReactViewPager.Adapter
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:92: error: cannot find symbol
      post(measureAndLayout);
      ^
  symbol:   method post(Runnable)
  location: class ReactViewPager.Adapter
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:96: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:101: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:109: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:112: error: cannot find symbol
          new PageScrollEvent(getId(), position, positionOffset));
                              ^
  symbol:   method getId()
  location: class ReactViewPager.PageChangeListener
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:115: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:119: error: cannot find symbol
            new PageSelectedEvent(getId(), position));
                                  ^
  symbol:   method getId()
  location: class ReactViewPager.PageChangeListener
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:123: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:127: error: cannot find symbol
        case SCROLL_STATE_IDLE:
             ^
  symbol:   variable SCROLL_STATE_IDLE
  location: class ReactViewPager.PageChangeListener
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:130: error: cannot find symbol
        case SCROLL_STATE_DRAGGING:
             ^
  symbol:   variable SCROLL_STATE_DRAGGING
  location: class ReactViewPager.PageChangeListener
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:133: error: cannot find symbol
        case SCROLL_STATE_SETTLING:
             ^
  symbol:   variable SCROLL_STATE_SETTLING
  location: class ReactViewPager.PageChangeListener
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:140: error: cannot find symbol
        new PageScrollStateChangedEvent(getId(), pageScrollState));
                                        ^
  symbol:   method getId()
  location: class ReactViewPager.PageChangeListener
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:152: error: cannot find symbol
    setOnPageChangeListener(new PageChangeListener());
    ^
  symbol:   method setOnPageChangeListener(ReactViewPager.PageChangeListener)
  location: class ReactViewPager
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:153: error: cannot find symbol
    setAdapter(new Adapter());
    ^
  symbol:   method setAdapter(ReactViewPager.Adapter)
  location: class ReactViewPager
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:156: error: method does not override or implement a method from a supertype
  @Override
  ^
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:158: error: cannot find symbol
    return (Adapter) super.getAdapter();
                     ^
  symbol:   variable super
  location: class ReactViewPager
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:161: error: method does not override or implement a method from a supertype
  @Override
  ^
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:168: error: cannot find symbol
      if (super.onInterceptTouchEvent(ev)) {
          ^
  symbol:   variable super
  location: class ReactViewPager
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:169: error: incompatible types: ReactViewPager cannot be converted to View
        NativeGestureUtil.notifyNativeGestureStarted(this, ev);
                                                     ^
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:182: error: method does not override or implement a method from a supertype
  @Override
  ^
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:189: error: cannot find symbol
      return super.onTouchEvent(ev);
             ^
  symbol:   variable super
  location: class ReactViewPager
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:202: error: cannot find symbol
    setCurrentItem(item, animated);
    ^
  symbol:   method setCurrentItem(int,boolean)
  location: class ReactViewPager
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:203: error: cannot find symbol
    mEventDispatcher.dispatchEvent(new PageSelectedEvent(getId(), item));
                                                         ^
  symbol:   method getId()
  location: class ReactViewPager
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:212: error: method does not override or implement a method from a supertype
  @Override
  ^
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:214: error: cannot find symbol
    super.onAttachedToWindow();
    ^
  symbol:   variable super
  location: class ReactViewPager
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:217: error: cannot find symbol
    this.requestLayout();
        ^
  symbol: method requestLayout()
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:218: error: cannot find symbol
    post(measureAndLayout);
    ^
  symbol:   method post(Runnable)
  location: class ReactViewPager
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:225: error: cannot find symbol
              MeasureSpec.makeMeasureSpec(getWidth(), MeasureSpec.EXACTLY),
                                          ^
  symbol: method getWidth()
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:225: error: cannot find symbol
              MeasureSpec.makeMeasureSpec(getWidth(), MeasureSpec.EXACTLY),
                                                      ^
  symbol: variable MeasureSpec
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:225: error: cannot find symbol
              MeasureSpec.makeMeasureSpec(getWidth(), MeasureSpec.EXACTLY),
              ^
  symbol: variable MeasureSpec
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:226: error: cannot find symbol
              MeasureSpec.makeMeasureSpec(getHeight(), MeasureSpec.EXACTLY));
                                          ^
  symbol: method getHeight()
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:226: error: cannot find symbol
              MeasureSpec.makeMeasureSpec(getHeight(), MeasureSpec.EXACTLY));
                                                       ^
  symbol: variable MeasureSpec
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:226: error: cannot find symbol
              MeasureSpec.makeMeasureSpec(getHeight(), MeasureSpec.EXACTLY));
              ^
  symbol: variable MeasureSpec
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:227: error: cannot find symbol
      layout(getLeft(), getTop(), getRight(), getBottom());
             ^
  symbol: method getLeft()
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:227: error: cannot find symbol
      layout(getLeft(), getTop(), getRight(), getBottom());
                        ^
  symbol: method getTop()
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:227: error: cannot find symbol
      layout(getLeft(), getTop(), getRight(), getBottom());
                                  ^
  symbol: method getRight()
/Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPager.java:227: error: cannot find symbol
      layout(getLeft(), getTop(), getRight(), getBottom());
                                              ^
  symbol: method getBottom()
Note: /Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPagerManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/kevin/Projects/pinktoad/node_modules/@react-native-community/viewpager/android/src/main/java/com/reactnativecommunity/viewpager/ReactViewPagerManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
53 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-community-viewpager:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s

Error: Command failed with exit code 1 (EPERM): ./gradlew assembleDebug -x bundleReleaseJsAndAssets
    at makeError (/Users/kevin/.nvm/versions/node/v12.18.3/lib/node_modules/rnv/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/Users/kevin/.nvm/versions/node/v12.18.3/lib/node_modules/rnv/node_modules/execa/index.js:112:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Desktop (please complete the following information):**

-   OS: Big Sur
-   Node Version 12.18.3
-   RNV Version 0.31.3

**Comment by pauliusguzas** [comment]
@kevindsky Thanks for reporting this issue. Tried this myself and couldn't reproduce on `@flexn/template` with version `0.18.0-alpha.10` on rnv `0.37.0-canary.4`. Could you check again ant tell if this is reproduced with updated versions
