### ISSUE TITLE
doResolve is not a function

### ISSUE THREAD

**Issue by fanzhiri** [renative-org/renative#759]
rnv build -p androidwear -s release

show error

│ [ error ] [configure] doResolve is not a function
TypeError: doResolve is not a function
    at doResolve (/Users/slakofan/Gitee/rnv-project/wearpoem/node_modules/rnv/src/core/systemManager/fileutils.js:589:46)
    at Array.forEach (<anonymous>)
    at forEach (/Users/slakofan/Gitee/rnv-project/wearpoem/node_modules/rnv/src/core/systemManager/fileutils.js:585:17)
    at fixResolve (/Users/slakofan/Gitee/rnv-project/wearpoem/node_modules/rnv/src/core/systemManager/fileutils.js:613:28)
    at Array.forEach (<anonymous>)
    at forEach (/Users/slakofan/Gitee/rnv-project/wearpoem/node_modules/rnv/src/core/systemManager/fileutils.js:610:26)
    at sanitizeDynamicProps (/Users/slakofan/Gitee/rnv-project/wearpoem/node_modules/rnv/src/core/systemManager/fileutils.js:620:21)
    at Array.forEach (<anonymous>)
    at forEach (/Users/slakofan/Gitee/rnv-project/wearpoem/node_modules/rnv/src/core/systemManager/fileutils.js:610:26)
    at sanitizeDynamicProps (/Users/slakofan/Gitee/rnv-project/wearpoem/node_modules/rnv/src/core/systemManager/fileutils.js:620:21)

**Comment by mihaiblaga89** [comment]
what RNV version and what project are you trying to run this on? Are you using the hello-world template or is it a custom project?

**Comment by mihaiblaga89** [comment]
closing this for now, feel free to reopen if you still encounter the issue
