### ISSUE TITLE
Unable to run legacy project (0.32) after upgrading to 0.33

### ISSUE THREAD

**Issue by ali-sao** [renative-org/renative#766]
**Unable to run  rnv run -p platform**
I was able to run the app before updating to 33

1. Run command `rnv run -p webos`
2. See error : `Cannot destructure property 'buildCoreWebpackProject' of '_rnv.WebpackUtils' as it is undefined.`

**Full stacktrace**
`[ error ] Cannot destructure property 'buildCoreWebpackProject' of '_rnv.WebpackUtils' as it is undefined.
TypeError: Cannot destructure property 'buildCoreWebpackProject' of '_rnv.WebpackUtils' as it is undefined.
    at Object.buildCoreWebpackProject (/Users/myUserName/Desktop/myProject/node_modules/@rnv/engine-rn-web/src/sdks/sdk-webos/index.js:20:9)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/myUserName/Desktop/myProject/node_modules/@rnv/engine-rn-web/src/sdks/index.js:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/myUserName/Desktop/myProject/node_modules/@rnv/engine-rn-web/src/tasks/task.rnv.run.js:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/myUserName/Desktop/myProject/node_modules/@rnv/engine-rn-web/src/index.js:3:1)
│`

-   OS: macOS Monterey 
-   Node Version :16.12.0
-   RNV Version : 0.33.0

**Screenshots**
<img width="1122" alt="Screen Shot 2021-12-14 at 4 22 29 PM" src="https://user-images.githubusercontent.com/6895166/146017207-761a66ed-e87a-41c8-af98-c60215baf70d.png">

<img width="1533" alt="Screen Shot 2021-12-14 at 4 22 51 PM" src="https://user-images.githubusercontent.com/6895166/146017241-77e0cb11-c5e9-4a4b-b853-716668966dd2.png">

@pavjacko , I believe it's nicer than it looks

**Comment by mihaiblaga89** [comment]
@ali-sao can you check your package.json if the rnv-engine-rn-web's version matches the rnv version? All engines should match the rnv's version.

**Comment by mihaiblaga89** [comment]
closing this for now, feel free to reopen if you still encounter the issue
