### ISSUE TITLE
Unable to run webos due to propTypes error in react-native-gesture-handler

### ISSUE THREAD

**Issue by danielz-nenda** [renative-org/renative#801]
**Describe the bug**
I'm trying to run my app on webOs. It's working fine on AndroidTV platform. The app is based on the blank template.

**To Reproduce**

1. Run command 'rnv run -p webos --hosted'
2. See white page with below error in Chrome Developer Console

**Expected behavior**
The app to show it's content

**Screenshots or copy&paste**
Uncaught TypeError: Cannot read properties of undefined (reading 'propTypes')
    at t.default (createNativeWrapper.js:38:20)
    at Object.<anonymous> (GestureComponents.web.js:23:31)
    at T (bootstrap:789:22)
    at n (bootstrap:100:12)
    at Object.<anonymous> (GestureHandler.js:10:1)
    at T (bootstrap:789:22)
    at n (bootstrap:100:12)
    at Object.<anonymous> (Swipeable.js:10:1)
    at T (bootstrap:789:22)
    at n (bootstrap:100:12)

**Desktop (please complete the following information):**

-   OS: Mac OSX 11.6.2 (M1)
-   Node Version v14.17.0
-   RNV Version 0.35.0 (also tried 0.34.0)

**Additional context**
I've tried to exclude the react-native-gesture-handler plugin for the webOs platform in renative.json, but that didn't have any effect and it's still included in the build.

**Comment by danielz-nenda** [comment]
This can be temporarily solved by overriding the version of  react-native-gesture-handler with the lastest v1:
` "react-native-gesture-handler": "1.10.3",`

**Comment by danielz-nenda** [comment]
I have to reopen this issue. It did indeed fix the propTypes TypeError on webOS but it breaks the plugin for AndroidTV. So it's only a solution for users that just need to run webOS, which isn't a great solution.

**Comment by GabrieleKaceviciute** [comment]
@danielz-nenda thanks for reporting, is this still reproduced on latest version?
