### ISSUE TITLE
Unable to `rnv run` when using `engine-rn-web` in `0.36.0-canary.12`

### ISSUE THREAD

**Issue by dotted** [renative-org/renative#839]
**Describe the bug**
See title

**To Reproduce**
1. Create new project with starter template
2. In `renative.json` make web platform use `engine-rn-web` engine
    ```
    "platforms": {
        "web": {
            "engine": "engine-rn-web"
        }
    },
    ```
3. `rnv run - p web` 

**Expected behavior**
No error and project runs as normal

**Screenshots or copy&paste**
```
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 3/23/2022, 9:37:01 AM                                         │
│  $ rnv run -p web                                                            │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.36.0-canary.12                                          │
│  Project Name ($package.name): spreadArrayIssue                              │
│  Project Version ($package.version): 0.1.0                                   │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): web                                                          │
│  Engine ($.platforms.web.engine): engine-rn-web                              │
│  Template: @rnv/template-starter@0.36.0-canary.12                            │
│  App Config (-c): app                                                        │
│  Build Scheme (-s): debug                                                    │
│  Supported Platforms: web                                                    │
│  Env Info: linux | x64 | node v16.14.2                                       │
│  Executed Time: 0h:2m:5s:422ms                                               │
│                                                                              │
│ [ warn ] [configure] Your appConfig/base/assets/web existis but engine engine-rn-web requires some additional assets:
public/index.html
│ [ error ] [run] Cannot use 'in' operator to search for '0' in /home/bo/test/spreadArrayIssue/platformAssets
TypeError: Cannot use 'in' operator to search for '0' in /home/bo/test/spreadArrayIssue/platformAssets
    at __spreadArray (/home/bo/test/spreadArrayIssue/node_modules/tslib/tslib.js:208:27)
    at module.exports (/home/bo/test/spreadArrayIssue/node_modules/@rnv/sdk-webpack/src/config/webpack.config.js:324:51)
    at /home/bo/test/spreadArrayIssue/node_modules/@rnv/sdk-webpack/src/scripts/start.js:71:20
    at new Promise (<anonymous>)
    at /home/bo/test/spreadArrayIssue/node_modules/@rnv/sdk-webpack/src/scripts/start.js:37:28
    at step (/home/bo/test/spreadArrayIssue/node_modules/tslib/tslib.js:143:27)
    at Object.next (/home/bo/test/spreadArrayIssue/node_modules/tslib/tslib.js:124:57)
    at /home/bo/test/spreadArrayIssue/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/home/bo/test/spreadArrayIssue/node_modules/tslib/tslib.js:113:16)
│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/app_web                                                    │
└──────────────────────────────────────────────────────────────────────────────┘
```

**Desktop (please complete the following information):**

-   OS: Ubuntu 20.04 on WSL2
-   Node Version v16.14.2
-   RNV Version 0.36.0-canary.12

**Additional context**
`0.36.0-canary.8` doesn't have this issue

Further, how come you keep changing between `engine-rn-web` and `engine-rn-next` as the default engine for web platform, it is rather confusing you keep switching between the two.

**Comment by mihaiblaga89** [comment]
@dotted #847 PR should fix that. However there are some warnings generated, working on fixing them as we speak. I'll publish a new version as soon as it's fixed
