### ISSUE TITLE
'rnv run' throws error

### ISSUE THREAD

**Issue by pauliusguzas** [renative-org/renative#911]
**Describe the bug**
`rnv run` throws error

**To Reproduce**
1. Create new project with `rnv new` and choose `template-starter`
2. Do `rnv run` -> error

**Expected behavior**
Cli should ask to choose desired platform

**Screenshots or copy&paste**

```
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 9/8/2022, 2:23:38 PM                                          │
│  $ rnv run                                                                   │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.36.2-canary.4                                           │
│  Project Name ($package.name): renativeTestuk                                │
│  Project Version ($package.version): 0.1.0                                   │
│  Workspace ($.workspaceID): rnv                                              │
│  Build Scheme (-s): debug                                                    │
│  Env Info: darwin | x64 | node v16.14.2                                      │
│  Executed Time: 0h:1m:12s:221ms                                              │
│                                                                              │
│ [ error ] Cannot find module 'react-native/package.json'
Require stack:
- /Users/pauliusguzas/Desktop/renativeTestuk/node_modules/@react-native-windows/cli/lib-commonjs/healthChecks.js
- /Users/pauliusguzas/Desktop/renativeTestuk/node_modules/@react-native-windows/cli/lib-commonjs/index.js
- /Users/pauliusguzas/Desktop/renativeTestuk/node_modules/@rnv/engine-rn-windows/dist/sdks/sdk-windows/index.js
- /Users/pauliusguzas/Desktop/renativeTestuk/node_modules/@rnv/engine-rn-windows/dist/sdks/index.js
- /Users/pauliusguzas/Desktop/renativeTestuk/node_modules/@rnv/engine-rn-windows/dist/tasks/task.rnv.build.js
- /Users/pauliusguzas/Desktop/renativeTestuk/node_modules/@rnv/engine-rn-windows/dist/index.js
- /Users/pauliusguzas/.config/yarn/global/node_modules/rnv/dist/core/engineManager/index.js
- /Users/pauliusguzas/.config/yarn/global/node_modules/rnv/dist/core/runtimeManager/index.js
- /Users/pauliusguzas/.config/yarn/global/node_modules/rnv/dist/cli/index.js
- /Users/pauliusguzas/.config/yarn/global/node_modules/rnv/dist/index.js
- /Users/pauliusguzas/.config/yarn/global/node_modules/rnv/bin/index.js
Error: Cannot find module 'react-native/package.json'
Require stack:
- /Users/pauliusguzas/Desktop/renativeTestuk/node_modules/@react-native-windows/cli/lib-commonjs/healthChecks.js
- /Users/pauliusguzas/Desktop/renativeTestuk/node_modules/@react-native-windows/cli/lib-commonjs/index.js
- /Users/pauliusguzas/Desktop/renativeTestuk/node_modules/@rnv/engine-rn-windows/dist/sdks/sdk-windows/index.js
- /Users/pauliusguzas/Desktop/renativeTestuk/node_modules/@rnv/engine-rn-windows/dist/sdks/index.js
- /Users/pauliusguzas/Desktop/renativeTestuk/node_modules/@rnv/engine-rn-windows/dist/tasks/task.rnv.build.js
- /Users/pauliusguzas/Desktop/renativeTestuk/node_modules/@rnv/engine-rn-windows/dist/index.js
- /Users/pauliusguzas/.config/yarn/global/node_modules/rnv/dist/core/engineManager/index.js
- /Users/pauliusguzas/.config/yarn/global/node_modules/rnv/dist/core/runtimeManager/index.js
- /Users/pauliusguzas/.config/yarn/global/node_modules/rnv/dist/cli/index.js
- /Users/pauliusguzas/.config/yarn/global/node_modules/rnv/dist/index.js
- /Users/pauliusguzas/.config/yarn/global/node_modules/rnv/bin/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at Object.<anonymous> (/Users/pauliusguzas/Desktop/renativeTestuk/node_modules/@react-native-windows/cli/src/healthChecks.ts:5:36)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.patchedRequire [as require] (/Users/pauliusguzas/Desktop/renativeTestuk/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at require (node:internal/modules/cjs/helpers:102:18)
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘
pauliusguzas@Pauliuss-MBP renativeTestuk %
```

**Desktop (please complete the following information):**

-   OS: Monterey 12.3.1
-   Node Version 16.14.2
-   RNV Version 0.36.2-canary.4

**Additional context**
Template used @rnv/template-starter@0.36.2-canary.4

**Comment by pauliusguzas** [comment]
Duplicate to https://github.com/renative-org/renative/issues/893
