### ISSUE TITLE
WearOS app not running on Wear OS Simualtor API 30

### ISSUE THREAD

**Issue by RiteshJariwala** [renative-org/renative#957]
I am trying to build a simple project for the wear os application. When running it on simulator i am getting the  following  error:

Unable to load script. Make  sure you're running Metro (run 'npx react-native start')  or that  your bundle 'index.androidwear.bundle'  is packaged correctly for release.

Anyone can guide me what i am doing wrong here?

I just followed "rnv new" command and created androidwear platform app.

**Comment by GabrieleKaceviciute** [comment]
@RiteshJariwala thanks for reporting this issue. What versions were you using of rnv, node?
I've tested on
OS: macOS Monterey 12.6
Node Version: v16.14.2
RNV Version: 0.37.0-canary.13
and this error occurs:
```🚀  SUMMARY | 6/16/2023, 5:36:13 PM                                         │
│  $ rnv run -p androidwear                                                    │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.37.0-canary.13                                          │
│  Project Name ($package.name): 957                                           │
│  Project Version ($package.version): 0.1.0                                   │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): androidwear                                                  │
│  Engine ($.platforms.androidwear.engine): engine-rn                          │
│  Template: @rnv/template-starter@0.37.0-canary.13                            │
│  App Config (-c): app                                                        │
│  Build Scheme (-s): debug                                                    │
│  Target (-t): Wear_OS_Square_API_30                                          │
│  Supported Platforms: androidwear                                            │
│  Env Info: darwin | x64 | node v16.14.2                                      │
│  Executed Time: 0h:0m:17s:561ms                                              │
│                                                                              │
│ [ success ] [run] Found active emulator! emulator-5554. Will use it
│ [ error ] [run] COMMAND:

./gradlew assembleDebug -x bundleReleaseJsAndAssets

FAILED with ERROR:

FAILURE: Build failed with an exception.

* Where:
Script '/Users/gabriele/Desktop/support/957/node_modules/react-native/react.gradle' line: 34

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > Couldn't determine CLI location. Please set `project.ext.react.cliPath` to the path of the react-native cli.js

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 742ms

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9.1/userguide/command_line_interface.html#sec:command_line_warnings

Command failed with exit code 1: ./gradlew assembleDebug -x bundleReleaseJsAndAssets

FAILURE: Build failed with an exception.

* Where:
Script '/Users/gabriele/Desktop/support/957/node_modules/react-native/react.gradle' line: 34

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > Couldn't determine CLI location. Please set `project.ext.react.cliPath` to the path of the react-native cli.js

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 742ms

> Configure project :app
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9.1/userguide/command_line_interface.html#sec:command_line_warnings


FAILURE: Build failed with an exception.

* Where:
Script '/Users/gabriele/Desktop/support/957/node_modules/react-native/react.gradle' line: 34

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > Couldn't determine CLI location. Please set `project.ext.react.cliPath` to the path of the react-native cli.js

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 742ms

Error: Command failed with exit code 1: ./gradlew assembleDebug -x bundleReleaseJsAndAssets

FAILURE: Build failed with an exception.

* Where:
Script '/Users/gabriele/Desktop/support/957/node_modules/react-native/react.gradle' line: 34

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > Couldn't determine CLI location. Please set `project.ext.react.cliPath` to the path of the react-native cli.js

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 742ms

> Configure project :app
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9.1/userguide/command_line_interface.html#sec:command_line_warnings
    at makeError (/Users/gabriele/Desktop/support/957/node_modules/rnv/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/gabriele/Desktop/support/957/node_modules/rnv/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)


│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/app_androidwear                                            │
└──────────────────────────────────────────────────────────────────────────────┘

**Comment by ElenaDiachenko** [comment]
1.0.0-canary.1 
`[ task ] [run] _runGradleApp[1]
✔ Executing: npx react-native run-android --mode=Debug --no-packager --deviceId=emulator-5554

⠏ INFO    | Setting display: 0 configuration to: 360x360, dpi: 320x320error Command failed with exit code 1: ./gradlew tasks

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/olenadiachenko/GitHub/renative/packages/template-starter/platformBuilds/template_androidwear/app/build.gradle' line: 22

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not read script '/Users/olenadiachenko/GitHub/renative/node_modules/react-native/react.gradle' as it does not exist.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 789ms
Configuration on demand is an incubating feature.

> Configure project :app
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.
Error: Command failed with exit code 1: ./gradlew tasks

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/olenadiachenko/GitHub/renative/packages/template-starter/platformBuilds/template_androidwear/app/build.gradle' line: 22

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not read script '/Users/olenadiachenko/GitHub/renative/node_modules/react-native/react.gradle' as it does not exist.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 789ms
Configuration on demand is an incubating feature.

> Configure project :app
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.
    at makeError (/Users/olenadiachenko/GitHub/renative/node_modules/execa/lib/error.js:60:11)
    at module.exports.sync (/Users/olenadiachenko/GitHub/renative/node_modules/execa/index.js:194:17)
    at getGradleTasks (/Users/olenadiachenko/GitHub/renative/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/listAndroidTasks.js:53:32)
    at getTaskNames (/Users/olenadiachenko/GitHub/renative/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/getTaskNames.js:21:73)
    at runOnSpecificDevice (/Users/olenadiachenko/GitHub/renative/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:184:55)
    at buildAndRun (/Users/olenadiachenko/GitHub/renative/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:167:12)
    at Object.runAndroid [as func] (/Users/olenadiachenko/GitHub/renative/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:100:10)
    at async Command.handleAction (/Users/olenadiachenko/GitHub/renative/node_modules/@react-native-community/cli/build/index.js:111:9)
COMMAND: 

npx react-native run-android --mode=Debug --no-packager --deviceId=emulator-5554 

FAILED with ERROR: 

Command failed with exit code 1: npx react-native run-android --mode=Debug --no-packager --deviceId=emulator-5554

Error: Command failed with exit code 1: npx react-native run-android --mode=Debug --no-packager --deviceId=emulator-5554
    at makeError (/Users/olenadiachenko/GitHub/renative/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/olenadiachenko/GitHub/renative/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)



 $ rnv run -p androidwear - Done! 🚀
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 10/6/2023, 5:06:18 PM                                         │
│  $ rnv run -p androidwear                                                    │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 1.0.0-canary.1                                            │
│  Project Name ($package.name): @rnv/template-starter                         │
│  Project Version ($package.version): 1.0.0-canary.1                          │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): androidwear                                                  │
│  Engine ($.platforms.androidwear.engine): engine-rn                          │
│  App Config (-c): template                                                   │
│  Build Scheme (-s): debug                                                    │
│  Target (-t): Android_Wear_Round_API_28                                      │
│  Supported Platforms: androidwear                                            │
│  Env Info: darwin | x64 | node v18.18.0                                      │
│  Executed Time: 0h:0m:42s:768ms                                              │
│                                                                              │
│ [ error ] [configure] Cannot write file. source path doesn't exists: /Users/olenadiachenko/GitHub/renative/packages/engine-rn/templates/platforms/androidwear/app/src/main/java/rnv_template/MainActivity.java.tpl
│ [ error ] [configure] Cannot write file. source path doesn't exists: /Users/olenadiachenko/GitHub/renative/packages/engine-rn/templates/platforms/androidwear/app/src/main/java/rnv_template/MainApplication.java.tpl
│ [ error ] [configure] Cannot write file. source path doesn't exists: /Users/olenadiachenko/GitHub/renative/packages/engine-rn/templates/platforms/androidwear/app/src/debug/java/rnv_template/ReactNativeFlipper.java.tpl
│ [ error ] [configure] Cannot write file. source path doesn't exists: /Users/olenadiachenko/GitHub/renative/packages/engine-rn/templates/platforms/androidwear/app/src/release/java/rnv_template/ReactNativeFlipper.java.tpl
│ [ success ] [run] Found active emulator! emulator-5554. Will use it
│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/template_androidwear                                       │`

**Comment by GabrieleKaceviciute** [comment]
It works on 1.0.0-canary.8

**Comment by GabrieleKaceviciute** [comment]
1.0.0-rc.4 ->
```
✖ FAILED: react-native bundle --platform android --dev false --assets-dest /Users/gabriele/Desktop/tests/asds/platformBuilds/app_androidwear/app/src/main/res --entry-file index.js --bundle-output /Users/gabriele/Desktop/tests/asds/platformBuilds/app_androidwear/app/src/main/assets/index.bundle --config=metro.config.js
[ info ] [run] ANDROID PACKAGE FAILED
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 12/19/2023, 3:52:34 PM                                        │
│  $ npx rnv run -p androidwear                                                │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 1.0.0-rc.4                                                │
│  Project Name ($package.name): asds                                          │
│  Project Version ($package.version): 0.1.0                                   │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): androidwear                                                  │
│  Engine ($.platforms.androidwear.engine): engine-rn                          │
│  Template: @rnv/template-starter@1.0.0-rc.4                                  │
│  App Config (-c): app                                                        │
│  Build Scheme (-s): debug                                                    │
│  Target (-t): Wear_OS_Square_API_30                                          │
│  Supported Platforms: androidwear                                            │
│  Env Info: darwin | x64 | node v18.14.2                                      │
│  Executed Time: 0h:2m:29s:232ms                                              │
│                                                                              │
│ [ success ] [project configure] /react-native-gesture-handler/ios/Handlers/RNHoverHandler.m requires override by: /rnv/pluginTemplates/react-native-gesture-handler/overrides.json. FIXING...DONE
│ [ success ] [project configure] /react-native-gesture-handler/ios/RNGestureHandlerButtonComponentView.mm requires override by: /rnv/pluginTemplates/react-native-gesture-handler/overrides.json. FIXING...DONE
│ [ success ] [project configure] /@react-native-community/cli-platform-ios/build/tools/listIOSDevices.js requires override by: /rnv/pluginTemplates/@react-native-community/cli-platform-ios/overrides@11.3.7.json. FIXING...DONE
│ [ success ] [project configure] /@react-native-community/cli-platform-ios/build/tools/findMatchingSimulator.js requires override by: /rnv/pluginTemplates/@react-native-community/cli-platform-ios/overrides@11.3.7.json. FIXING...DONE
│ [ success ] [project configure] /@react-native-community/cli-platform-ios/build/commands/runIOS/index.js requires override by: /rnv/pluginTemplates/@react-native-community/cli-platform-ios/overrides@11.3.7.json. FIXING...DONE
│ [ success ] [run] Found active emulator! emulator-5554. Will use it
│ [ error ] [run] COMMAND:

react-native bundle --platform android --dev false --assets-dest /Users/gabriele/Desktop/tests/asds/platformBuilds/app_androidwear/app/src/main/res --entry-file index.js --bundle-output /Users/gabriele/Desktop/tests/asds/platformBuilds/app_androidwear/app/src/main/assets/index.bundle --config=metro.config.js

FAILED with ERROR:

error SHA-1 for file /Users/gabriele/Desktop/tests/asds/index.js (/Users/gabriele/Desktop/tests/asds/index.js) is not computed.
 Potential causes:
 1) You have symlinks in your project - watchman does not follow symlinks.
 2) Check `blockList` in your metro.config.js and make sure it isn't excluding the file path.
ReferenceError: SHA-1 for file /Users/gabriele/Desktop/tests/asds/index.js (/Users/gabriele/Desktop/tests/asds/index.js) is not computed.
 Potential causes:
 1) You have symlinks in your project - watchman does not follow symlinks.
 2) Check `blockList` in your metro.config.js and make sure it isn't excluding the file path.
 at DependencyGraph.getSha1 (/Users/gabriele/Desktop/tests/asds/node_modules/metro/src/node-haste/DependencyGraph.js:217:13)
 at Transformer._getSha1 (/Users/gabriele/Desktop/tests/asds/node_modules/metro/src/Bundler.js:26:26)

Command failed with exit code 1: react-native bundle --platform android --dev false --assets-dest /Users/gabriele/Desktop/tests/asds/platformBuilds/app_androidwear/app/src/main/res --entry-file index.js --bundle-output /Users/gabriele/Desktop/tests/asds/platformBuilds/app_androidwear/app/src/main/assets/index.bundle --config=metro.config.js
warn From React Native 0.72, your metro.config.js file should extend'@react-native/metro-config'. Please see the React Native 0.72 changelog, or copy the template at:
https://github.com/facebook/react-native/blob/main/packages/react-native/template/metro.config.js
warn Falling back to internal defaults.
error SHA-1 for file /Users/gabriele/Desktop/tests/asds/index.js (/Users/gabriele/Desktop/tests/asds/index.js) is not computed.
         Potential causes:
           1) You have symlinks in your project - watchman does not follow symlinks.
           2) Check `blockList` in your metro.config.js and make sure it isn't excluding the file path.
                Welcome to Metro v0.76.7
              Fast - Scalable - Integrated


ReferenceError: SHA-1 for file /Users/gabriele/Desktop/tests/asds/index.js (/Users/gabriele/Desktop/tests/asds/index.js) is not computed.
         Potential causes:
           1) You have symlinks in your project - watchman does not follow symlinks.
           2) Check `blockList` in your metro.config.js and make sure it isn't excluding the file path.
    at DependencyGraph.getSha1 (/Users/gabriele/Desktop/tests/asds/node_modules/metro/src/node-haste/DependencyGraph.js:217:13)
    at Transformer._getSha1 (/Users/gabriele/Desktop/tests/asds/node_modules/metro/src/Bundler.js:26:26)
    at Transformer.transformFile (/Users/gabriele/Desktop/tests/asds/node_modules/metro/src/DeltaBundler/Transformer.js:106:19)
    at Bundler.transformFile (/Users/gabriele/Desktop/tests/asds/node_modules/metro/src/Bundler.js:60:30)
    at Object.transform (/Users/gabriele/Desktop/tests/asds/node_modules/metro/src/lib/transformHelpers.js:143:12)
    at Graph._processModule (/Users/gabriele/Desktop/tests/asds/node_modules/metro/src/DeltaBundler/Graph.js:257:20)
    at Graph._traverseDependenciesForSingleFile (/Users/gabriele/Desktop/tests/asds/node_modules/metro/src/DeltaBundler/Graph.js:249:5)
    at async Promise.all (index 0)
    at Graph.initialTraverseDependencies (/Users/gabriele/Desktop/tests/asds/node_modules/metro/src/DeltaBundler/Graph.js:233:5)
    at DeltaCalculator._getChangedDependencies (/Users/gabriele/Desktop/tests/asds/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:229:25)
    at DeltaCalculator.getDelta (/Users/gabriele/Desktop/tests/asds/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:112:16)
    at DeltaBundler.buildGraph (/Users/gabriele/Desktop/tests/asds/node_modules/metro/src/DeltaBundler.js:54:5)
    at IncrementalBundler.buildGraphForEntries (/Users/gabriele/Desktop/tests/asds/node_modules/metro/src/IncrementalBundler.js:66:19)
    at IncrementalBundler.buildGraph (/Users/gabriele/Desktop/tests/asds/node_modules/metro/src/IncrementalBundler.js:146:19)
    at Server.build (/Users/gabriele/Desktop/tests/asds/node_modules/metro/src/Server.js:104:32)
    at buildBundleWithConfig (/Users/gabriele/Desktop/tests/asds/node_modules/@react-native-community/cli-plugin-metro/build/commands/bundle/buildBundle.js:88:20)
info Run CLI with --verbose flag for more details.

warn From React Native 0.72, your metro.config.js file should extend'@react-native/metro-config'. Please see the React Native 0.72 changelog, or copy the template at:
https://github.com/facebook/react-native/blob/main/packages/react-native/template/metro.config.js
warn Falling back to internal defaults.
error SHA-1 for file /Users/gabriele/Desktop/tests/asds/index.js (/Users/gabriele/Desktop/tests/asds/index.js) is not computed.
         Potential causes:
           1) You have symlinks in your project - watchman does not follow symlinks.
           2) Check `blockList` in your metro.config.js and make sure it isn't excluding the file path.

Error: Command failed with exit code 1: react-native bundle --platform android --dev false --assets-dest /Users/gabriele/Desktop/tests/asds/platformBuilds/app_androidwear/app/src/main/res --entry-file index.js --bundle-output /Users/gabriele/Desktop/tests/asds/platformBuilds/app_androidwear/app/src/main/assets/index.bundle --config=metro.config.js
warn From React Native 0.72, your metro.config.js file should extend'@react-native/metro-config'. Please see the React Native 0.72 changelog, or copy the template at:
https://github.com/facebook/react-native/blob/main/packages/react-native/template/metro.config.js
warn Falling back to internal defaults.
error SHA-1 for file /Users/gabriele/Desktop/tests/asds/index.js (/Users/gabriele/Desktop/tests/asds/index.js) is not computed.
         Potential causes:
           1) You have symlinks in your project - watchman does not follow symlinks.
           2) Check `blockList` in your metro.config.js and make sure it isn't excluding the file path.
                Welcome to Metro v0.76.7
              Fast - Scalable - Integrated


ReferenceError: SHA-1 for file /Users/gabriele/Desktop/tests/asds/index.js (/Users/gabriele/Desktop/tests/asds/index.js) is not computed.
         Potential causes:
           1) You have symlinks in your project - watchman does not follow symlinks.
           2) Check `blockList` in your metro.config.js and make sure it isn't excluding the file path.
    at DependencyGraph.getSha1 (/Users/gabriele/Desktop/tests/asds/node_modules/metro/src/node-haste/DependencyGraph.js:217:13)
    at Transformer._getSha1 (/Users/gabriele/Desktop/tests/asds/node_modules/metro/src/Bundler.js:26:26)
    at Transformer.transformFile (/Users/gabriele/Desktop/tests/asds/node_modules/metro/src/DeltaBundler/Transformer.js:106:19)
    at Bundler.transformFile (/Users/gabriele/Desktop/tests/asds/node_modules/metro/src/Bundler.js:60:30)
    at Object.transform (/Users/gabriele/Desktop/tests/asds/node_modules/metro/src/lib/transformHelpers.js:143:12)
    at Graph._processModule (/Users/gabriele/Desktop/tests/asds/node_modules/metro/src/DeltaBundler/Graph.js:257:20)
    at Graph._traverseDependenciesForSingleFile (/Users/gabriele/Desktop/tests/asds/node_modules/metro/src/DeltaBundler/Graph.js:249:5)
    at async Promise.all (index 0)
    at Graph.initialTraverseDependencies (/Users/gabriele/Desktop/tests/asds/node_modules/metro/src/DeltaBundler/Graph.js:233:5)
    at DeltaCalculator._getChangedDependencies (/Users/gabriele/Desktop/tests/asds/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:229:25)
    at DeltaCalculator.getDelta (/Users/gabriele/Desktop/tests/asds/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:112:16)
    at DeltaBundler.buildGraph (/Users/gabriele/Desktop/tests/asds/node_modules/metro/src/DeltaBundler.js:54:5)
    at IncrementalBundler.buildGraphForEntries (/Users/gabriele/Desktop/tests/asds/node_modules/metro/src/IncrementalBundler.js:66:19)
    at IncrementalBundler.buildGraph (/Users/gabriele/Desktop/tests/asds/node_modules/metro/src/IncrementalBundler.js:146:19)
    at Server.build (/Users/gabriele/Desktop/tests/asds/node_modules/metro/src/Server.js:104:32)
    at buildBundleWithConfig (/Users/gabriele/Desktop/tests/asds/node_modules/@react-native-community/cli-plugin-metro/build/commands/bundle/buildBundle.js:88:20)
info Run CLI with --verbose flag for more details.
    at makeError (/Users/gabriele/Desktop/tests/asds/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/gabriele/Desktop/tests/asds/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)


│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/app_androidwear                                            │
└──────────────────────────────────────────────────────────────────────────────┘
➜  ~/Desktop/tests/asds
```

**Comment by ElenaDiachenko** [comment]
1.0.0-rc.8. Can’t reproduce.
