### ISSUE TITLE
[MacOS] [Regression] Can't run template starter

### ISSUE THREAD

**Issue by ZymanteG** [renative-org/renative#968]
**Describe the bug**
Rnv does not install on MacOS simulator.

**To Reproduce**
1. Create new project with `rnv new` and choose `template-starter `
2. Do `rnv run -p macOS`

**Expected behavior**
MacOS app launches.

**Screenshots or copy&paste**

```
✖ FAILED: xcodebuild-workspace /Users/pauliusguzas/Desktop/rnv/platformBuilds/app_macos/RNVApp.xcworkspace -scheme RNVApp -configuration Debug -derivedDataPath /Users/pauliusguzas/Desktop/rnv/platformBuilds/app_macos/build/RNVApp -destination platform=macOS build -allowProvisioningUpdates
✖ FAILED: open platformBuilds/app_macos/build/RNVApp/Build/Products/Debug-maccatalyst/RNVApp.app
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 3/15/2023, 5:43:56 PM                                         │
│  $ rnv run -p macos                                                          │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.37.0-canary.4                                           │
│  Project Name ($package.name): rnv                                           │
│  Project Version ($package.version): 0.1.0                                   │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): macos                                                        │
│  Engine ($.platforms.macos.engine): engine-rn                                │
│  Template: @rnv/template-starter@0.37.0-canary.4                             │
│  App Config (-c): app                                                        │
│  Build Scheme (-s): debug                                                    │
│  Supported Platforms: macos                                                  │
│  Env Info: darwin | x64 | node v16.14.2                                      │
│  Executed Time: 0h:2m:6s:872ms                                               │
│                                                                              │
│ [ error ] [run] COMMAND:

open platformBuilds/app_macos/build/RNVApp/Build/Products/Debug-maccatalyst/RNVApp.app

FAILED with ERROR:

The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10827 "kLSNoExecutableErr: The executable is missing" UserInfo={_LSLine=4101, _LSFunction=_LSOpenStuffCallLocal}

Command failed with exit code 1: open platformBuilds/app_macos/build/RNVApp/Build/Products/Debug-maccatalyst/RNVApp.app
The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10827 "kLSNoExecutableErr: The executable is missing" UserInfo={_LSLine=4101, _LSFunction=_LSOpenStuffCallLocal}

The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10827 "kLSNoExecutableErr: The executable is missing" UserInfo={_LSLine=4101, _LSFunction=_LSOpenStuffCallLocal}

Error: Command failed with exit code 1: open platformBuilds/app_macos/build/RNVApp/Build/Products/Debug-maccatalyst/RNVApp.app
The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10827 "kLSNoExecutableErr: The executable is missing" UserInfo={_LSLine=4101, _LSFunction=_LSOpenStuffCallLocal}
    at makeError (/Users/pauliusguzas/Desktop/rnv/node_modules/rnv/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/pauliusguzas/Desktop/rnv/node_modules/rnv/node_modules/execa/index.js:118:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)


│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/app_macos/RNVApp.xcworkspace                               │
└──────────────────────────────────────────────────────────────────────────────┘
pauliusguzas@Pauliuss-MacBook-Pro rnv %
```

**Desktop (please complete the following information):**

- OS: macOS Montery 12.6.3
- Node Version: v16.15.1
- RNV Version: 0.37.0-canary.4

**Comment by pauliusguzas** [comment]
Fixed in 0.37.0-canary.9
